version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./samples/Poc.Api
      dockerfile: Dockerfile
    ports:
      - "5149:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Keycloak__Authority=http://keycloak:8080/realms/poc
      - Keycloak__Audience=account
    depends_on:
      - keycloak

  yarp:
    build:
      context: .
      dockerfile: samples/Poc.Yarp/Dockerfile
    ports:
      - "5198:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Keycloak__Authority=http://keycloak:8080/realms/poc
      - Keycloak__Url=http://keycloak:8080
      - Keycloak__Audience=account
      - FrontEnd__RedirectAfterLogin=http://frontend:3000
      - ReverseProxy__Clusters__apiCluster__Destinations__destination1__Address=http://api:8080
    depends_on:
      - api

  frontend:
    build:
      context: ./samples/poc-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - yarp

volumes:
  postgres_data: